# Site settings
title: Cathexis
email: your-email@domain.com
description: "the concentration of mental energy onto one particular person, idea, or object"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty

collections:
  volume_Testing:
    output: true